### ISSUE TITLE
SetADOrganizationalUnitForComputer - Issue with multiple child domains.

### ISSUE THREAD

**Issue by ReverendRhyme** [NickolajA/ConfigMgrWebService#18]
https://github.com/NickolajA/ConfigMgrWebService/blob/4bbb9ec5c50ff767e936bc63e91f61b6ee804377/ConfigMgrWebService/ConfigMgrWebService.asmx.cs#L5673

Using the Global Catalog instead of LDAP 

If you update line 5673 

from:
string currentDomain = String.Format("LDAP://{0}", defaultNamingContext);

to:
 string currentDomain = String.Format("GC://{0}", defaultNamingContext);

**Comment by NickolajA** [comment]
I'll add this to 1.8.0 and re-upload the newly released version.
