### ISSUE TITLE
GetCMPrimaryDeviceByUser filters by wrong parameter

### ISSUE THREAD

**Issue by Nightlurker** [NickolajA/ConfigMgrWebService#2]
It looks like the function GetCMPrimaryDeviceByUser filters by the wrong parameter. The query is identical to the one used in GetCMPrimaryUserByDevice and yelds the same result.

Solution:
Change the query from "WHERE ResourceName" to "WHERE UniqueUserName"

**Comment by jholl016** [comment]
I can confirm that this bug exists in the latest build, and that updating the query does fix it.

I also recommend updating the documentation for this method.  For the query to work correctly, I have to pass the username using the format '[domain]\\[username]' (using two backslashes).  Using only a single backslash returns a 'generic failure' message.

**Comment by NickolajA** [comment]
Thank you guys for reporting this. It will be addressed in version 1.5.0. I'll also update the documentation.
