### ISSUE TITLE
AD calls are working, but not CM calls.

### ISSUE THREAD

**Issue by brianfgonzalez** [NickolajA/ConfigMgrWebService#28]
I followed the manual installation guide and all seems to be configured properly.  I provided my domain admin credentials as this is my lab to the IIS app pool, so I know it's not a permissions issue.

I intend on using this with OSDFrontEnd eventually.  I'm running SCCM 1910.

![2020-04-21_14-37-57_EmptyConfigMgrWebserviceResults](https://user-images.githubusercontent.com/1973673/79903176-a0170e80-83e0-11ea-8e68-7aa5d1abb80d.png)
![2020-04-21_14-52-10_InetLogs](https://user-images.githubusercontent.com/1973673/79903178-a0170e80-83e0-11ea-8671-42e54bcc9746.png)
![2020-04-21_15-06-59_ConfigMgrWebServiceWebConfig](https://user-images.githubusercontent.com/1973673/79903882-d6a15900-83e1-11ea-992d-f71e40621a81.png)
![2020-04-21_15-04-57_ConfigMgrWebService](https://user-images.githubusercontent.com/1973673/79903883-d739ef80-83e1-11ea-94d7-56f09b090a38.png)
![2020-04-21_15-11-22_SCCMSiteServerRoles](https://user-images.githubusercontent.com/1973673/79904314-7c54c800-83e2-11ea-9a14-93ed0b12af3b.png)

**Comment by ChadSimmons** [comment]
Try populating the SQLServer key in web.config with the ConfigMgr SQL server then restarting IIS.  I vaguely remember doing that some time back.

**Comment by NickolajA** [comment]
This was taken offline on Twitter and there was not any permissions configured in ConfigMgr for the app pool's identity.
